CREATE TABLE IF NOT EXISTS `countries` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `name` varchar(80) NOT NULL,
    `continent` varchar(30) DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=59 DEFAULT CHARSET=utf8;

INSERT INTO `countries` (`id`, `name`, `continent`) VALUES
(1, 'Algeria', 'Africa'),
(2, 'Angola', 'Africa'),
(3, 'Benin', 'Africa'),
(4, 'Botswana', 'Africa'),
(5, 'Burkina Faso', 'Africa'),
(6, 'Burundi', 'Africa'),
(7, 'Cameroon', 'Africa'),
(8, 'Cape Verde', 'Africa'),
(9, 'Central African Republic', 'Africa'),
(10, 'Chad', 'Africa'),
(11, 'Comoros', 'Africa'),
(12, 'Congo', 'Africa'),
(13, 'Congo, Democratic Republic of the Congo', 'Africa'),
(14, 'Ivory Coast', 'Africa'),
(15, 'Djibouti', 'Africa'),
(16, 'Egypt', 'Africa'),
(17, 'Equatorial Guinea', 'Africa'),
(18, 'Eritrea', 'Africa'),
(19, 'Ethiopia', 'Africa'),
(20, 'Gabon', 'Africa'),
(21, 'Gambia', 'Africa'),
(22, 'Ghana', 'Africa'),
(23, 'Guinea', 'Africa'),
(24, 'Guinea-Bissau', 'Africa'),
(25, 'Kenya', 'Africa'),
(26, 'Lesotho', 'Africa'),
(27, 'Liberia', 'Africa'),
(28, 'Libyan Arab Jamahiriya', 'Africa'),
(29, 'Madagascar', 'Africa'),
(30, 'Malawi', 'Africa'),
(31, 'Mali', 'Africa'),
(32, 'Mauritania', 'Africa'),
(33, 'Mauritius', 'Africa'),
(34, 'Mayotte', 'Africa'),
(35, 'Morocco', 'Africa'),
(36, 'Mozambique', 'Africa'),
(37, 'Namibia', 'Africa'),
(38, 'Niger', 'Africa'),
(39, 'Nigeria', 'Africa'),
(40, 'Reunion', 'Africa'),
(41, 'Rwanda', 'Africa'),
(42, 'Saint Helena', 'Africa'),
(43, 'Sao Tome and Principe', 'Africa'),
(44, 'Senegal', 'Africa'),
(45, 'Seychelles', 'Africa'),
(46, 'Sierra Leone', 'Africa'),
(47, 'Somalia', 'Africa'),
(48, 'South Africa', 'Africa'),
(49, 'South Sudan', 'Africa'),
(50, 'Sudan', 'Africa'),
(51, 'Swaziland', 'Africa'),
(52, 'Tanzania, United Republic of', 'Africa'),
(53, 'Togo', 'Africa'),
(54, 'Tunisia', 'Africa'),
(55, 'Uganda', 'Africa'),
(56, 'Western Sahara', 'Africa'),
(57, 'Zambia', 'Africa'),
(58, 'Zimbabwe', 'Africa');