CREATE TABLE IF NOT EXISTS `asia` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `name` varchar(80) NOT NULL,
    `continent` varchar(30) DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=56 DEFAULT CHARSET=utf8;

INSERT INTO `asia` (`id`, `name`, `continent`) VALUES
(1, 'Afghanistan', 'Asia'),
(2, 'Armenia', 'Asia'),
(3, 'Azerbaijan', 'Asia'),
(4, 'Bahrain', 'Asia'),
(5, 'Bangladesh', 'Asia'),
(6, 'Bhutan', 'Asia'),
(7, 'British Indian Ocean Territory', 'Asia'),
(8, 'Brunei Darussalam', 'Asia'),
(9, 'Cambodia', 'Asia'),
(10, 'China', 'Asia'),
(11, 'Christmas Island', 'Asia'),
(12, 'Cocos (Keeling) Islands', 'Asia'),
(13, 'Cyprus', 'Asia'),
(14, 'Georgia', 'Asia'),
(15, 'Hong Kong', 'Asia'),
(16, 'India', 'Asia'),
(17, 'Indonesia', 'Asia'),
(18, 'Iran, Islamic Republic of', 'Asia'),
(19, 'Iraq', 'Asia'),
(20, 'Israel', 'Asia'),
(21, 'Japan', 'Asia'),
(22, 'Jordan', 'Asia'),
(23, 'Kazakhstan', 'Asia'),
(24, 'Korea, Democratic Peoples Republic of', 'Asia'),
(25, 'Korea, Republic of', 'Asia'),
(26, 'Kuwait', 'Asia'),
(27, 'Kyrgyzstan', 'Asia'),
(28, 'Lao Peoples Democratic Republic', 'Asia'),
(29, 'Lebanon', 'Asia'),
(30, 'Macao', 'Asia'),
(31, 'Malaysia', 'Asia'),
(32, 'Maldives', 'Asia'),
(33, 'Mongolia', 'Asia'),
(34, 'Myanmar', 'Asia'),
(35, 'Nepal', 'Asia'),
(36, 'Oman', 'Asia'),
(37, 'Pakistan', 'Asia'),
(38, 'Palestinian Territory, Occupied', 'Asia'),
(39, 'Philippines', 'Asia'),
(40, 'Qatar', 'Asia'),
(41, 'Russian Federation', 'Asia'),
(42, 'Saudi Arabia', 'Asia'),
(43, 'Singapore', 'Asia'),
(44, 'Sri Lanka', 'Asia'),
(45, 'Syrian Arab Republic', 'Asia'),
(46, 'Taiwan, Province of China', 'Asia'),
(47, 'Tajikistan', 'Asia'),
(48, 'Thailand', 'Asia'),
(49, 'Timor-Leste', 'Asia'),
(50, 'Turkey', 'Asia'),
(51, 'Turkmenistan', 'Asia'),
(52, 'United Arab Emirates', 'Asia'),
(53, 'Uzbekistan', 'Asia'),
(54, 'Viet Nam', 'Asia'),
(55, 'Yemen', 'Asia');